import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rob MacKay",
  // Shown in search results and in the link preview when the URL is pasted into
  // Slack, LinkedIn or an email client — which is exactly how this page gets
  // shared, so it should not still read "Generated by create next app".
  description:
    "An interactive résumé for Robert MacKay: ask about his experience, what he has built, and how this application works.",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
