import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // protoc-gen-es output. Regenerated by `make generate` from the .proto, so
    // a lint finding here is a report about a code generator we do not own and
    // cannot be fixed in place — the next generate would undo it.
    "src/gen/**",
  ]),
]);

export default eslintConfig;
